apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
    version: v2
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
        version: v2
    spec:
      containers:
      - image: durgaletchumy/reverseproxy
        name: reverseproxy
        command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


